// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTbTaskStep = "task_step_log"

// TvTask mapped from table <tv_task>
type TbTaskStep struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID         string    `gorm:"column:task_id" json:"task_id"`
	VideoID        string    `gorm:"column:video_id;not null" json:"video_id"`
	TaskName      string    `gorm:"column:task_name;not null" json:"task_name"`
	Status         string    `gorm:"column:status" json:"status"`
	StartTime      time.Time `gorm:"column:start_time" json:"start_time"`
	EndTime        time.Time `gorm:"column:end_time" json:"end_time"`
	ErrorMessage   string    `gorm:"column:error_message" json:"error_message"`
	Result         string    `gorm:"column:result" json:"result"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TvTask's table name
func (*TbTaskStep) TableName() string {
	return TableNameTbTaskStep
}
